/*
 * CardPlayPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cd.java.contact.panel;

import javax.swing.JFrame;

import cd.java.contact.*;

/**
 *
 * @author  __USER__
 */
public class CardPlayPanel extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2694243950868341573L;
	/** Creates new form CardPlayPanel */
	private JFrame mainFrame = null;
	private PersonCols pcs = null;
	private UserCols ucs = null;
	private UserInfo ui = null;
	private ContactPerson cp = null;
	private int index = 0;

	public CardPlayPanel(JFrame mainFrame, PersonCols pcs, UserCols ucs,
			UserInfo ui, ContactPerson cp, int index) {
		super();
		this.mainFrame = mainFrame;
		this.pcs = pcs;
		this.ucs = ucs;
		this.ui = ui;
		this.cp = cp;
		this.index = index;
		initComponents();
		System.out.println(index);
	}

	/*	ContactPerson [] tmpcps = pcs.getAll();
		 if(cp != null){
			 index = cp.getNumId()-1;
			 lab_showname.setText(cp.getName());
			 lab_showpiny.setText(cp.getBirthday());
			 lab_showaddress.setText(cp.getAddress());
			 lab_showbirth.setText(cp.getBirthday());
			 lab_showphone.setText(cp.getPhonenum());
			 this.cp = null;
		 }else{
			 lab_showname.setText(tmpcps[index].getName());
			 lab_showpiny.setText(tmpcps[index].getBirthday());
			 lab_showaddress.setText(tmpcps[index].getAddress());
			 lab_showbirth.setText(tmpcps[index].getBirthday());
			 lab_showphone.setText(tmpcps[index].getPhonenum());
		 }
		 if(index == 0){
			 btn_pre.setEnabled(false);
			 btn_next.setEnabled(true);
		 }else if(index == (tmpcps.length-1)){
			 btn_pre.setEnabled(true);
			 btn_next.setEnabled(false);
		 }else{
			 btn_pre.setEnabled(true);
			 btn_next.setEnabled(true);
		 }*/
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		btn_pre = new javax.swing.JButton();
		btn_next = new javax.swing.JButton();
		lab_name = new javax.swing.JLabel();
		lab_showname = new javax.swing.JLabel();
		lab_piny = new javax.swing.JLabel();
		lab_showpiny = new javax.swing.JLabel();
		lab_address = new javax.swing.JLabel();
		lab_showaddress = new javax.swing.JLabel();
		lab_birthday = new javax.swing.JLabel();
		lab_showbirth = new javax.swing.JLabel();
		lab_phone = new javax.swing.JLabel();
		lab_showphone = new javax.swing.JLabel();
		lab_welcome = new javax.swing.JLabel();
		btn_return = new javax.swing.JButton();

		setBackground(new java.awt.Color(0, 204, 204));
		
		ContactPerson [] tmpcps = pcs.getAll();
		if(pcs.getLength() > 0){
			if(cp != null){
				 index = cp.getNumId()-1;
				 lab_showname.setText(cp.getName());
				 lab_showpiny.setText(cp.getBirthday());
				 lab_showaddress.setText(cp.getAddress());
				 lab_showbirth.setText(cp.getBirthday());
				 lab_showphone.setText(cp.getPhonenum());
				 this.cp = null;
			 }else{
				 lab_showname.setText(tmpcps[index].getName());
				 lab_showpiny.setText(tmpcps[index].getBirthday());
				 lab_showaddress.setText(tmpcps[index].getAddress());
				 lab_showbirth.setText(tmpcps[index].getBirthday());
				 lab_showphone.setText(tmpcps[index].getPhonenum());
			 }
			 if(index == 0){
				 btn_pre.setEnabled(false);
				 btn_next.setEnabled(true);
			 }
			 if(index == (tmpcps.length-1)){
				 btn_pre.setEnabled(true);
				 btn_next.setEnabled(false);
			 }
			 if(index ==0 && index == (tmpcps.length-1)){
				 btn_pre.setEnabled(false);
				 btn_next.setEnabled(false);
			 }
			 if(index !=0 && index != (tmpcps.length-1)){
				 btn_pre.setEnabled(true);
				 btn_next.setEnabled(true);
			 }
		}else{
			System.out.println("联系人列表为空，请添加联系人.");
		}

		btn_pre.setText("\u4e0a\u4e00\u9875");
		btn_pre.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_preActionPerformed(evt);
			}
		});

		btn_next.setText("\u4e0b\u4e00\u9875");
		btn_next.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_nextActionPerformed(evt);
			}
		});

		lab_name.setText("\u59d3\u540d");

		lab_showname.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		lab_piny.setText("\u62fc\u97f3\u59d3\u540d");

		lab_showpiny.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		lab_address.setText("\u5730\u5740");

		lab_showaddress.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		lab_birthday.setText("\u751f\u65e5");

		lab_showbirth.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		lab_phone.setText("\u624b\u673a\u53f7\u7801");

		lab_showphone.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		lab_welcome.setBackground(new java.awt.Color(204, 0, 255));
		lab_welcome.setFont(new java.awt.Font("宋体", 0, 18));
		lab_welcome.setText("\u4e2a\u4eba\u4fe1\u606f\u5c55\u793a");

		btn_return.setText("\u8fd4\u56de\u4e3b\u754c\u9762");
		btn_return.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_returnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(55, 55,
																		55)
																.addComponent(
																		lab_welcome)
																.addGap(26, 26,
																		26))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(59, 59,
																		59)
																.addComponent(
																		btn_return)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		btn_pre)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		btn_next))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(35, 35,
																		35)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						lab_piny)
																				.addComponent(
																						lab_name)
																				.addComponent(
																						lab_address)
																				.addComponent(
																						lab_phone)
																				.addComponent(
																						lab_birthday))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						lab_showpiny,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						100,
																						Short.MAX_VALUE)
																				.addComponent(
																						lab_showname,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						100,
																						Short.MAX_VALUE)
																				.addComponent(
																						lab_showaddress,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						lab_showbirth,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						lab_showphone,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))))
								.addContainerGap(48, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addComponent(lab_welcome)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lab_name)
												.addComponent(
														lab_showname,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														22,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lab_piny)
												.addComponent(
														lab_showpiny,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														22,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		lab_showaddress,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		22,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		lab_showbirth,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		22,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		lab_address)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		lab_birthday)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lab_phone)
												.addComponent(
														lab_showphone,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														22,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										22, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btn_pre)
												.addComponent(btn_next)
												.addComponent(btn_return))
								.addGap(27, 27, 27)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {
		this.index++;
		this.mainFrame.getContentPane().removeAll();
		CardPlayPanel cardpanel = new CardPlayPanel(this.mainFrame, this.pcs,
				this.ucs, this.ui, this.cp, this.index);
		this.mainFrame.getContentPane().add(cardpanel);
		this.mainFrame.getContentPane().validate();
	}

	private void btn_preActionPerformed(java.awt.event.ActionEvent evt) {
		index--;
		this.mainFrame.getContentPane().removeAll();
		CardPlayPanel cardpanel = new CardPlayPanel(this.mainFrame, this.pcs,
				this.ucs, this.ui, this.cp, this.index);
		this.mainFrame.getContentPane().add(cardpanel);
		this.mainFrame.getContentPane().validate();
	}

	private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {
		this.mainFrame.getContentPane().removeAll();
		this.mainFrame.getContentPane().add(
				new MainContactPanel(this.mainFrame, this.ucs, this.pcs,
						this.ui));
		this.mainFrame.getContentPane().validate();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btn_next;
	private javax.swing.JButton btn_pre;
	private javax.swing.JButton btn_return;
	private javax.swing.JLabel lab_address;
	private javax.swing.JLabel lab_birthday;
	private javax.swing.JLabel lab_name;
	private javax.swing.JLabel lab_phone;
	private javax.swing.JLabel lab_piny;
	private javax.swing.JLabel lab_showaddress;
	private javax.swing.JLabel lab_showbirth;
	private javax.swing.JLabel lab_showname;
	private javax.swing.JLabel lab_showphone;
	private javax.swing.JLabel lab_showpiny;
	private javax.swing.JLabel lab_welcome;
	// End of variables declaration//GEN-END:variables

}