/*
 * MainContactPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cd.java.contact.panel;

import javax.swing.JFrame;

import cd.java.contact.*;

/**
 *
 * @author  __USER__
 */
public class MainContactPanel extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9134383243159614452L;
	/** Creates new form MainContactPanel */
	private JFrame mainFrame = null;
	private UserCols ucs = null;
	private PersonCols pcs = null;
	private UserInfo ui = null;
	private ContactPerson cp = null;
	private String fileName = "./contact.xml";
	private int index = 0;

	public MainContactPanel(JFrame mainFrame, UserCols ucs, PersonCols pcs,
			UserInfo ui) {
		super();
		this.mainFrame = mainFrame;
		this.ucs = ucs;
		this.pcs = pcs;
		this.ui = ui;
		initComponents();
	}

	/*list_contact.setModel(new javax.swing.AbstractListModel() {
		String[] strings = new String[pcs.getLength()];
		ContactPerson [] tmpcps = pcs.getAll();
		{
			for(int i=0; i<strings.length; i++){
				strings[i] = tmpcps[i].getName()+"\t\t"+tmpcps[i].getPhonenum();
			}
		}

		public int getSize() {
			return strings.length;
		}

		public Object getElementAt(int i) {
			return strings[i];
		}
	});
	lab_user.setText(this.ui.getUserName());*/

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	@SuppressWarnings("serial")
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		list_contact = new javax.swing.JList();
		btn_add = new javax.swing.JButton();
		btn_delete = new javax.swing.JButton();
		btn_update = new javax.swing.JButton();
		btn_cardplay = new javax.swing.JButton();
		lab_welcome = new javax.swing.JLabel();
		lab_user = new javax.swing.JLabel();
		btn_modifyuser = new javax.swing.JButton();
		btn_exit = new javax.swing.JButton();

		setBackground(new java.awt.Color(0, 204, 204));

		list_contact.setModel(new javax.swing.AbstractListModel() {
			String[] strings = new String[pcs.getLength()];
			ContactPerson [] tmpcps = pcs.getAll();
			{
				for(int i=0; i<strings.length; i++){
					strings[i] = tmpcps[i].getName()+"\t\t"+tmpcps[i].getPhonenum();
				}
			}

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		lab_user.setText(this.ui.getUserName());
		
		list_contact
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		list_contact
				.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
					public void valueChanged(
							javax.swing.event.ListSelectionEvent evt) {
						list_contactValueChanged(evt);
					}
				});
		jScrollPane1.setViewportView(list_contact);

		btn_add.setText("\u6dfb\u52a0\u8054\u7cfb\u4eba");
		btn_add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_addActionPerformed(evt);
			}
		});

		btn_delete.setText("\u5220\u9664\u8054\u7cfb\u4eba");
		btn_delete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_deleteActionPerformed(evt);
			}
		});

		btn_update.setText("\u66f4\u65b0\u4e2a\u4eba\u4fe1\u606f");
		btn_update.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_updateActionPerformed(evt);
			}
		});

		btn_cardplay.setText("\u5e7b\u706f\u7247\u89c2\u770b");
		btn_cardplay.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_cardplayActionPerformed(evt);
			}
		});

		lab_welcome.setFont(new java.awt.Font("华文行楷", 0, 24));
		lab_welcome
				.setText("\u6b22\u8fce\u6765\u5230\u901a\u8baf\u5f55\u4e3b\u754c\u9762\uff01");

		lab_user.setFont(new java.awt.Font("宋体", 0, 18));

		btn_modifyuser.setText("\u4fee\u6539\u7528\u6237\u4fe1\u606f");
		btn_modifyuser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_modifyuserActionPerformed(evt);
			}
		});

		btn_exit.setText("\u9000\u51fa");
		btn_exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_exitActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		lab_welcome)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		lab_user,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		76,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(10, 10,
																		10)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										btn_add)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										btn_delete)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										btn_exit))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jScrollPane1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										201,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																												.addComponent(
																														btn_update,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														btn_modifyuser,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														btn_cardplay,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE))))))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lab_welcome)
												.addComponent(lab_user))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		164,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(12, 12,
																		12)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						btn_add)
																				.addComponent(
																						btn_delete)
																				.addComponent(
																						btn_exit))
																.addContainerGap(
																		20,
																		Short.MAX_VALUE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		btn_modifyuser)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		78,
																		Short.MAX_VALUE)
																.addComponent(
																		btn_update)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		btn_cardplay)
																.addGap(66, 66,
																		66)))));
	}// </editor-fold>
	//GEN-END:initComponents

	private void list_contactValueChanged(
			javax.swing.event.ListSelectionEvent evt) {
		String str = list_contact.getSelectedValue().toString();
		String name = str.substring(0, str.indexOf("\t\t"));
		cp = pcs.get(name);
		this.index = cp.getNumId()-1;
	}

	private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {
		this.mainFrame.getContentPane().removeAll();
		this.mainFrame.getContentPane()
				.add(new LoginPanel(this.mainFrame, ucs));
		this.mainFrame.getContentPane().validate();
	}

	private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {
		if(cp != null){
			pcs.delete(this.cp);
			pcs.sort();
			pcs.reSetNumId(pcs);
			cp = null;
			
			ContactToXML cxml = new ContactToXML();
			cxml.WriteContactToXML(pcs, fileName);
			
			this.mainFrame.getContentPane().removeAll();
			this.mainFrame.getContentPane()
					.add(new MainContactPanel(this.mainFrame, this.ucs, this.pcs, this.ui));
			this.mainFrame.getContentPane().validate();
		}else{
			System.out.println("请从左边列表中选择一个联系人删除.");
		}
	}

	private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {
		this.mainFrame.getContentPane().removeAll();
		this.mainFrame.getContentPane()
				.add(new AddContactPanel(this.mainFrame, this.ucs, this.pcs,
						this.ui));
		this.mainFrame.getContentPane().validate();
	}

	private void btn_cardplayActionPerformed(java.awt.event.ActionEvent evt) {
		if(pcs.getLength() > 0){
			this.mainFrame.getContentPane().removeAll();
			this.mainFrame.getContentPane().add(
					new CardPlayPanel(this.mainFrame, this.pcs, this.ucs, this.ui,
							this.cp, this.index));
			this.mainFrame.getContentPane().validate();
		}else{
			System.out.println("联系人链表为空，请添加联系人.");
		}
	}

	private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {
		if(this.cp != null){
			this.mainFrame.getContentPane().removeAll();
			this.mainFrame.getContentPane().add(
					new PersonPanel(this.mainFrame, this.pcs, this.ucs, this.ui,
							this.cp));
			this.mainFrame.getContentPane().validate();
		}else{
			System.out.println("请从左边列表中选择一个联系人.");
		}
	}

	private void btn_modifyuserActionPerformed(java.awt.event.ActionEvent evt) {
		this.mainFrame.getContentPane().removeAll();
		this.mainFrame.getContentPane()
				.add(new ModifyUserPanel(this.mainFrame, this.pcs, this.ucs,
						this.ui));
		this.mainFrame.getContentPane().validate();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btn_add;
	private javax.swing.JButton btn_cardplay;
	private javax.swing.JButton btn_delete;
	private javax.swing.JButton btn_exit;
	private javax.swing.JButton btn_modifyuser;
	private javax.swing.JButton btn_update;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lab_user;
	private javax.swing.JLabel lab_welcome;
	private javax.swing.JList list_contact;
	// End of variables declaration//GEN-END:variables

}