/*
 *
 * Created on __DATE__, __TIME__
 * RegisterPanel.java
 */

package cd.java.contact.panel;

import javax.swing.JFrame;

import cd.java.contact.*;

/**
 *
 * @author  __USER__
 */
public class ModifyUserPanel extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6016810717832896148L;

	private JFrame mainFrame = null;
	private PersonCols pcs = null;
	private UserCols ucs = null;
	private UserInfo ui = null;
	private String fileName = "./user.xml";
	private String validate = "3RjO";

	/** Creates new form RegisterPanel */
	public ModifyUserPanel(JFrame mainFrame, PersonCols pcs, UserCols ucs,
			UserInfo ui) {
		super();
		this.mainFrame = mainFrame;
		this.pcs = pcs;
		this.ucs = ucs;
		this.ui = ui;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lab_welcome = new javax.swing.JLabel();
		lab_image = new javax.swing.JLabel();
		lab_validate = new javax.swing.JLabel();
		lab_repasswd = new javax.swing.JLabel();
		lab_passwd = new javax.swing.JLabel();
		lab_username = new javax.swing.JLabel();
		lab_email = new javax.swing.JLabel();
		btn_reget = new javax.swing.JButton();
		edit_passwd = new javax.swing.JPasswordField();
		edit_repasswd = new javax.swing.JPasswordField();
		edit_email = new javax.swing.JTextField();
		edit_validate = new javax.swing.JTextField();
		btn_ok = new javax.swing.JButton();
		btn_cancel = new javax.swing.JButton();
		lab_showname = new javax.swing.JLabel();
		lab_showrepasswd = new javax.swing.JLabel();
		lab_showpasswd = new javax.swing.JLabel();
		
		lab_showname.setText(this.ui.getUserName());
		edit_email.setText(ui.getEmail());
		

		setBackground(new java.awt.Color(0, 204, 204));

		lab_welcome.setFont(new java.awt.Font("华文行楷", 0, 18));
		lab_welcome
				.setText("\u6b22\u8fce\u6765\u5230\u4e2a\u4eba\u4fe1\u606f\u754c\u9762\uff01");

		lab_image.setFont(new java.awt.Font("宋体", 2, 24));
		lab_image.setText(this.validate);
		lab_image.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		lab_validate.setText("\u9a8c\u8bc1\u7801");

		lab_repasswd.setText("\u8bf7\u786e\u8ba4\u5bc6\u7801");

		lab_passwd.setText("\u8bf7\u8f93\u5165\u5bc6\u7801");

		lab_username.setText("\u7528\u6237\u540d\uff1a");

		lab_email.setText("\u7535\u5b50\u90ae\u7bb1");

		btn_reget.setText("\u91cd\u65b0\u83b7\u53d6\u9a8c\u8bc1\u7801");
		btn_reget.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_regetActionPerformed(evt);
			}
		});

		btn_ok.setText("\u4fee\u6539");
		btn_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_okActionPerformed(evt);
			}
		});

		btn_cancel.setText("\u53d6\u6d88");
		btn_cancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_cancelActionPerformed(evt);
			}
		});

		lab_showrepasswd.setText("(6-16\u4f4d\u6570\u5b57\u5b57\u6bcd)");

		lab_showpasswd.setText("(6-16\u4f4d\u6570\u5b57\u5b57\u6bcd)");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(36, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														lab_image,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														lab_validate,
														javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														lab_repasswd,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														lab_passwd,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		lab_username)
																.addGap(6, 6, 6))
												.addComponent(
														lab_email,
														javax.swing.GroupLayout.Alignment.TRAILING))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(btn_reget)
												.addComponent(edit_passwd, 0,
														0, Short.MAX_VALUE)
												.addComponent(edit_repasswd, 0,
														0, Short.MAX_VALUE)
												.addComponent(
														edit_email,
														javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														edit_validate,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														124, Short.MAX_VALUE)
												.addComponent(lab_showname))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lab_showrepasswd)
												.addComponent(lab_showpasswd))
								.addGap(24, 24, 24))
				.addGroup(
						layout.createSequentialGroup().addGap(73, 73, 73)
								.addComponent(btn_ok).addGap(30, 30, 30)
								.addComponent(btn_cancel)
								.addContainerGap(144, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup().addGap(65, 65, 65)
								.addComponent(lab_welcome)
								.addContainerGap(87, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(6, 6, 6)
								.addComponent(lab_welcome)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lab_username)
												.addComponent(lab_showname))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						lab_passwd)
																				.addComponent(
																						edit_passwd,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						lab_repasswd)
																				.addComponent(
																						edit_repasswd,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						lab_email)
																				.addComponent(
																						edit_email,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						21,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(9, 9, 9)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						lab_validate)
																				.addComponent(
																						edit_validate,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						21,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						lab_image,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						26,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						btn_reget)))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		lab_showpasswd,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		20,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		lab_showrepasswd,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		20,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.CENTER)
												.addComponent(btn_ok)
												.addComponent(btn_cancel))
								.addGap(23, 23, 23)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {
		this.mainFrame.getContentPane().removeAll();
		this.mainFrame.getContentPane().add(
				new MainContactPanel(this.mainFrame, this.ucs, this.pcs,
						this.ui));
		this.mainFrame.getContentPane().validate();
	}

	private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {
		// 将窗体组件中的信息保存起来
		String name = lab_showname.getText();
		String passwd = String.valueOf(edit_passwd.getPassword());
		String repasswd = String.valueOf(edit_repasswd.getPassword());
		String email = edit_email.getText();
		String validate = edit_validate.getText();
		
		// 初始化一个检查信息的对象，对窗体组件中输入的用户名、密码、验证码进行验证
		CheckInfo check = new CheckInfo();
		if(check.checkPasswd(passwd)
				&& check.checkPasswd(repasswd) && check.checkEmail(email)){
			if(validate.compareToIgnoreCase(lab_image.getText()) == 0){
				if(passwd.compareTo(repasswd) == 0){
					UserInfo tmpui = new UserInfo();
					tmpui.setUserName(name);
					tmpui.setPasswd(passwd);
					tmpui.setEmail(email);
					this.ucs.update(ucs.get(name), tmpui);
					this.ucs.sort();
					
					UserToXML uxml = new UserToXML();
					uxml.WriteUserToXML(ucs, fileName);
					
					this.mainFrame.getContentPane().removeAll();
					
					this.mainFrame.getContentPane().add(
							new LoginPanel(this.mainFrame, this.ucs));
					this.mainFrame.getContentPane().validate();
				}else{
					System.out.println("两次密码不匹配，请重新输入密码.");
				}
			}else{
				System.out.println("验证码不正确.");
			}
		}else{
			System.out.println("用户信息格式不正确.");
		}
	}

	private void btn_regetActionPerformed(java.awt.event.ActionEvent evt) {
		edit_validate.setText("");
		CommonMethod cm = new CommonMethod();
		this.validate = cm.MakeValidate();
		
		lab_image.setText(this.validate);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btn_cancel;
	private javax.swing.JButton btn_ok;
	private javax.swing.JButton btn_reget;
	private javax.swing.JTextField edit_email;
	private javax.swing.JPasswordField edit_passwd;
	private javax.swing.JPasswordField edit_repasswd;
	private javax.swing.JTextField edit_validate;
	private javax.swing.JLabel lab_email;
	private javax.swing.JLabel lab_image;
	private javax.swing.JLabel lab_passwd;
	private javax.swing.JLabel lab_repasswd;
	private javax.swing.JLabel lab_showname;
	private javax.swing.JLabel lab_showpasswd;
	private javax.swing.JLabel lab_showrepasswd;
	private javax.swing.JLabel lab_username;
	private javax.swing.JLabel lab_validate;
	private javax.swing.JLabel lab_welcome;
	// End of variables declaration//GEN-END:variables

}